/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder: THREE.Mesh
    Cylinder_1: THREE.Mesh
    Cylinder_2: THREE.Mesh
  }
  materials: {
    Floor: THREE.MeshStandardMaterial
    Glass: THREE.MeshPhysicalMaterial
    Metal: THREE.MeshStandardMaterial
  }
}

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/InfinityTower.gltf') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Cylinder.geometry} material={materials.Floor} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder_1.geometry} material={materials.Glass} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder_2.geometry} material={materials.Metal} />
    </group>
  )
}

useGLTF.preload('/InfinityTower.gltf')
